---
- name: Install Redis
  apt: name={{item}} state=present
  with_items:
  - redis-server

- name: Configuring redis
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: Restart Redis

- name: Enable the Redis services to start automatically
  shell: update-rc.d redis-server defaults
  changed_when: False

- name: Sysctl configuration
  template: src=sysctl.j2 dest=/etc/sysctl.conf

- name: Sysctl configuration
  shell: sysctl vm.overcommit_memory=1
