---
- name: Add the Nginx source to the APT source list
  apt_repository: repo="ppa:nginx/stable" state=present
  tags:
    - nginx-installation

- name: Install Nginx
  apt: name={{item}} state=latest
  with_items:
   - nginx
   - nginx-extras
   - openssl
  tags:
    - nginx-installation

- name: Create directories for ssl, error_pages & deployment_info
  file: path={{item}} state=directory
  with_items:
   - /usr/share/nginx/deployment_info
   - /usr/share/nginx/error_pages
   - /etc/nginx/ssl
   - /etc/nginx/geoip
  tags:
    - nginx-configuration

- name: Copy and extraxt geoip
  unarchive: src={{item.src}} dest={{item.dest}} copy=yes
  with_items:
    - { src: roles/nginx/files/GeoIP.dat.zip, dest: /etc/nginx/geoip }
    - { src: roles/nginx/files/GeoLiteCity.dat.zip, dest: /etc/nginx/geoip }
  tags:
    - nginx-gioip-configuration

- name: Configure GeoIP
  lineinfile: dest=/etc/nginx/fastcgi_params line="{{item}}"
  with_items:
    - " "
    - "### SET GEOIP Variables ###"
    - fastcgi_param GEOIP_COUNTRY_CODE $geoip_country_code;
    - fastcgi_param GEOIP_COUNTRY_CODE3 $geoip_country_code3;
    - fastcgi_param GEOIP_COUNTRY_NAME $geoip_country_name;
    - "#"
    - fastcgi_param GEOIP_CITY_COUNTRY_CODE $geoip_city_country_code;
    - fastcgi_param GEOIP_CITY_COUNTRY_CODE3 $geoip_city_country_code3;
    - fastcgi_param GEOIP_CITY_COUNTRY_NAME $geoip_city_country_name;
    - fastcgi_param GEOIP_REGION $geoip_region;
    - fastcgi_param GEOIP_CITY $geoip_city;
    - fastcgi_param GEOIP_POSTAL_CODE $geoip_postal_code;
    - fastcgi_param GEOIP_CITY_CONTINENT_CODE $geoip_city_continent_code;
    - fastcgi_param GEOIP_LATITUDE $geoip_latitude;
    - fastcgi_param GEOIP_LONGITUDE $geoip_longitude;
  tags:
    - nginx-gioip-configuration

- name: Copy default index, error_pages & ssl certificates
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: '{{default_index}}', dest: '{{doc_root}}' }
    - { src: '{{error_page_404}}', dest: /usr/share/nginx/error_pages }
    - { src: '{{error_page_50x}}', dest: /usr/share/nginx/error_pages }
    - { src: '{{error_page_403}}', dest: /usr/share/nginx/error_pages }
    - { src: '{{ssl_crt_file}}', dest: /etc/nginx/ssl/ssl_crt.pem }
    - { src: '{{ssl_key_file}}', dest: /etc/nginx/ssl/ssl_key.pem }
  tags:
    - nginx-configuration

- name: Stop Nginx
  service: name=nginx state=stopped
  tags:
    - nginx-configuration

- name: Configure Nginx
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  tags:
    - nginx-configuration

- name: Configure Nginx virtualhost
  template: src={{item.src}} dest={{item.dest}}
  with_items:
  - { src: virtualhost.j2, dest: /etc/nginx/sites-available/default }
  - { src: virtualhost.j2, dest: /etc/nginx/sites-enabled/default }
  - { src: virtualhost_ssl.j2, dest: /etc/nginx/sites-available/default-ssl }
  - { src: virtualhost_ssl.j2, dest: /etc/nginx/sites-enabled/default-ssl }
  - { src: dhparam.pem, dest: /etc/nginx/ssl/dhparam.pem}
  tags:
    - nginx-virtualhost-configuration

- name: Start Nginx
  service: name=nginx state=started
  tags:
    - nginx-configuration
