---
- name: Add the playdeb APT key
  apt_key: url=http://archive.getdeb.net/getdeb-archive.key state=present

- name: Add playdeb repository
  apt_repository: repo="deb http://archive.getdeb.net/ubuntu xenial-getdeb games" state=present

- name: Install assault cube
  apt: name={{item}} state=present
  with_items:
  - assaultcube

- name: Setup init script
  template: src=assaultcube.j2 dest=/etc/init.d/assaultcube mode=0755

- name: Set assaultcube to start up by default
  shell: update-rc.d assaultcube defaults 95 10

#- name: Setup systemd file
#  template: src=assaultcube.service.j2 dest=/etc/systemd/system/assaultcube.service mode=0755

#- name: Start assaultcube
#  service: name=assaultcube state=started enabled=yes
