---
- name: Gather ec2 facts
  ec2_facts:
  when: dc_env == "aws"

- name: Set Host name
  hostname: name={{hostname}}
  tags:
    - set-hostname

- name: Replace default hosts file
  lineinfile: dest=/etc/hosts line='{{ansible_default_ipv4.address}} {{hostname}}.{{domain_name}} {{hostname}}'
  tags:
    - set-hostname

- name: Prevent IP Spoofing
  template: src=hosts.conf dest=/etc/host.conf
  tags:
    - set-hostname

- name: Update ec2 tags
  include: ec2-tags.yml
  when: dc_env == "aws"
