---
- name: Add the elasticsearch APT repository key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the Kibana APT repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/{{pl_kiban_major_version}}/apt stable main" state=present

- name: Install kibana
  apt: name={{item}} state=present
  with_items:
  - kibana={{pl_kiban_minor_version}}
  notify: kibana restart

#- name: Install x-pack
#This is failing
#  kibana_plugin: state=present name=x-pack plugin_bin=/usr/share/kibana/bin/kibana-plugin
#  shell: /usr/share/kibana/bin/kibana-plugin install x-pack

- name: Put Kibana on startup
  systemd: name=kibana enabled=yes daemon_reload=yes

- name: Configure kibana
  lineinfile: dest="/etc/kibana/kibana.yml" regexp="{{item.regexp}}" line="{{item.line}}" state=present backrefs=yes backup=yes
  with_items:
    - { regexp: 'server.port', line: 'server.port: {{pl_kibana_port}}' }
    - { regexp: 'server.host', line: 'server.host: {{ansible_ssh_host}}' }
    - { regexp: 'server.name', line: 'server.name: {{ht_cluster_name}}' }
    - { regexp: 'elasticsearch.url', line: 'elasticsearch.url: http://{{ht_elasticsearch_url}}' }
    - { regexp: 'kibana.index', line: 'kibana.index: .{{pl_kibana_index}}' }
  notify: kibana restart
