---
- name: Add the playdeb APT key
  apt_key: url=http://archive.getdeb.net/getdeb-archive.key state=present

- name: Add playdeb repository
  apt_repository: repo="deb http://archive.getdeb.net/ubuntu trusty-getdeb games" state=present

- name: Install enemy-territory
  apt: name={{item}} state=present
  with_items:
  - enemy-territory
  - lib32stdc++6

- name: Copy mod binaries
  unarchive: src={{item}} dest=/usr/share/games/enemy-territory copy=yes
  with_items:
  - silent.zip
  - pb.zip
#  - etpro-3_2_6.zip
#  - jaymod-2.0.3-linux.tar.gz
#  - nitmod_2.3.1.zip
#  - http://www.wolfzone.eu/download/wolfzone-linux64-160207.zip

- name: Copy omni-bot binaries
  unarchive: src=omni-bot_0_831_ET_linux.zip dest=/usr/share/games/enemy-territory copy=yes
  ignore_errors: True

- name: Configure enemy-territory
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'server.j2', dest: '/usr/share/games/enemy-territory/etmain/server.cfg' }
    - { src: 'silent.j2', dest: '/usr/share/games/enemy-territory/etmain/silent.cfg' }
    - { src: 'silent-banner.j2', dest: '/usr/share/games/enemy-territory/etmain/banner.cfg' }
    - { src: 'bot.j2', dest: '/usr/share/games/enemy-territory/etmain/bot.cfg' }
    - { src: 'silent-default.j2', dest: '/usr/share/games/enemy-territory/silent/default.cfg' }
    - { src: 'silent-shrubbot.j2', dest: '/usr/share/games/enemy-territory/silent/shrubbot.cfg' }
    - { src: 'omnibot.j2', dest: '/usr/share/games/enemy-territory/omni-bot/et/user/omnibot.cfg' }
    - { src: 'objectivecycle.j2', dest: '/usr/share/games/enemy-territory/etmain/objectivecycle.cfg' }
    - { src: 'admin.j2', dest: '/usr/share/games/enemy-territory/silent/database/admin.cfg' }
#    - { src: 'jaymod.j2', dest: '/usr/share/games/enemy-territory/etmain/jaymod.cfg' }
#    - { src: 'nitmod.j2', dest: '/usr/share/games/enemy-territory/etmain/nitmod.cfg' }

- name: Copy maps
  copy: src={{item}} dest=/usr/share/games/enemy-territory/etmain/
  with_items:
    - 2hide.pk3
    - 2tanks_171.pk3
    - 1944_beach.pk3
    - adlernest_2b.pk3
    - adlernest.pk3
    - airassault_fp1.pk3
    - alpine_assault_final.pk3
    - venice.pk3
    - v2base.pk3
    - supplydepot2.pk3
  tags:
    - copy-maps

- name: Extract maps
  shell: cd /usr/share/games/enemy-territory/etmain && unzip {{item}}
  with_items:
    - 2hide.pk3
    - 2tanks_171.pk3
    - 1944_beach.pk3
    - adlernest_2b.pk3
    - adlernest.pk3
    - airassault_fp1.pk3
    - alpine_assault_final.pk3
    - venice.pk3
    - v2base.pk3
    - supplydepot2.pk3
  ignore_errors: True
  tags:
    - copy-maps

- name: Copy init.d script
  template: src={{item.src}} dest={{item.dest}} mode=0755
  with_items:
    - { src: 'etded-silent.j2', dest: '/etc/init.d/etded-silent' }
#    - { src: 'etded-main-obj.j2', dest: '/etc/init.d/etded-main-obj' }
#    - { src: 'etded-pro-obj.j2', dest: '/etc/init.d/etded-pro-obj' }
#    - { src: 'etded-main-camp.j2', dest: '/etc/init.d/etded-main-camp' }
#    - { src: 'etded-pro-camp.j2', dest: '/etc/init.d/etded-pro-camp' }
#    - { src: 'etded-jaymod.j2', dest: '/etc/init.d/etded-jaymod' }
#    - { src: 'etded-wolfzone.j2', dest: '/etc/init.d/etded-wolfzone' }
#    - { src: 'etded-nitmod.j2', dest: '/etc/init.d/etded-nitmod' }
