---
- name: Install ntp
  apt: name={{ item }} state=present
  with_items:
  - ntp

- name: Configure ntp
  template: src=ntp.j2 dest=/etc/ntp.conf
  notify: Restart ntp

- name: Remove default time zone
  file: path=/etc/localtime state=absent
  changed_when: False

- name: Set local time
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
  changed_when: False
