---
- name: Add the elasticsearch APT repository key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the elasticsearch APT repository
  apt_repository: repo="deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" state=present

- name: Install elasticsearch
  apt: name={{item}} state=present force=yes
  with_items:
  - elasticsearch
  notify: Start elasticsearch

- name: Set elasticsearch to start up by default
  shell: sudo update-rc.d elasticsearch defaults 95 10
  changed_when: false
